### ISSUE TITLE
with a vignette

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvars#100]
## todos

- [x] update `DESCRIPTION` by 
  - [x] new version
  - [x] **bsvarSIGNs** mention
  - [x] citation of the vignette with arxiv doi
- [x] update website
  - [x] update description
  - [x] include the mention of the vignette
  - [ ] include *Resources* a new section fo vignette
  - [x] include stickers of **bsvarSIGNs** and **bsvar.org** and environ description
  - [x] new icons for scholar, arxiv, and bsky in about the author
- [x] update `NEWS`
- [x] update `CITATION`
- [x] checks
