### ISSUE TITLE
update help and documentation for generics

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvars#63]
- Other packages will rely on `estimate` (and other) generics. Their help files must be more general.
- They will also depend or import such functions as `compute_*`. They must have appropriate help and arguments checks.

## Todo's

- [ ] `estimate` documentation and args checks
- [x] `forecast` documentation and args checks
- [x] `compute_*` documentation and args checks
